apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment

spec:
  selector:
    matchLabels:
      app: nginx

  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: spring-kafka
        image: registry.gitlab.com/srinivasboini/kafka/spring-kafka-producer-1:20230520_051700
        ports:
        - containerPort: 80
